### PR TITLE
Added Events

### PR DESCRIPTION
**Pull request by foysalit**
Hi,
I have added a couple of events to the core. Check it out and let me know if you can merge it, please.
Cool plugin BTW :+1: 
Thanks
Foysal

### CODE REVIEW

**Comment by adchsm** [comment]
Hi there,

Thanks for this, it looks brilliant! I'll take a look and accept it when I've got a bit more time :)

Thanks, Adam

**Comment by NilAndNull** [comment]
I've tested on Chrome and it returns an error on api-usage.html

TypeError: undefined is not an object (evaluating 'mySlidebars.slidebars.on') 

Don't know why... I really need to learn JS...

**Comment by aaemnnosttv** [comment]
Thanks for the effort on this.  This has been something that the plugin has needed for a while.

A few thoughts in regards to the changes: I think it would be better for the events to be triggered within the `animate()` function.  For example, in the case of jQuery animation, the completed event should be called from the `complete` callback passed to the [jQuery animate](https://api.jquery.com/animate/) method.  `setTimeout` is probably necessary for the `translate`-based animation, but either way, I think the events should and could be managed from the animate function.

The events should also use a proper [event namespace](https://api.jquery.com/on/#event-names).

**Comment by adchsm** [comment]
Hey there,

Sorry I haven't been working on Sidebars much, however recently I have started developing a completely new version, where you can have multiple instances and top and bottom Slidebars!

It's still in early development, but it's functional and I have added events to it.

If you look at the dev.html file in the master, you'll see some basic usage. I'll get around to writing proper instructions soon

I'll close this pull request now as it doesn't really apply anymore, but thank you very much for submitting it, I have used to help me add events to the new version, I really appreciate it.

Thanks,

Adam

**Pull request closed without merging**
